### ISSUE TITLE
Additions to the chapter on exceptions

### ISSUE THREAD

**Issue by jbarnoud** [HowToThink/HowToThink#16]
The chapter on exceptions only shows bare `except`s. Also it does not mention the `else` keyword for `try`.

Is it overwhelming the students to add the missing bits?

**Comment by tBuLi** [comment]
I think we should at least warn against bare `except`'s and probably only use targeted ones in the examples. 

We should also include a word of caution on putting to much inside the `try`, only the thing you want to catch should be in there. The rest goes in the `else`, or possibly the `finally`.

I think that for completeness it might be good to mention all of this right? It might be a bit much, but that's why it's an appendix.

**Comment by pckroon** [comment]
Fixed by #19.
